### ISSUE TITLE
Error connecting to google drive

### ISSUE THREAD

**Issue by duckydee** [Willena/Google-Drive-Folder-Downloader#1]
I have my credentials.json, but it keeps giving me an error that it cant connect to google drive. What am I doing wrong?

**Comment by Willena** [comment]
To understand how the Google API works, I recommend the following resource: https://developers.google.com/drive/api/v3/about-sdk . And especially https://developers.google.com/drive/api/v3/quickstart/python. 

Once you have the credentials.json file, you can start the download.py script. The script will ask you to login and authorize the app. Once finished, a reusable token.json is generated, and you should be able to use the script. 

I'm regularly using the script, never had a problem with login...
